### ISSUE TITLE
JSCapstone

### ISSUE THREAD

**Issue by DilsherB** [DilsherB/JSCapstone#22]
https://github.com/DilsherB/JSCapstone/projects/1
Note: we are two person in this project

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻👋🏻

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


## Highlights
- Great job on set the kanban card 🔥🤩
- The issues are descriptive 💯✨

## Required Changes ♻️
_Check the comments under the review._

- [ ] I think you forget to assign each card to the team I can see that you wrote student A but it would b e great if you assign each card to the student itslef as well since this is one of the requirements and it is very useful to let it be clear that who wil do this task ✨💯🤩🔥 and don't forget to assign the grop tasks as well 💯💯💯


![image](https://user-images.githubusercontent.com/58553711/226597402-a41f29e9-bd36-457b-8722-076ec32332d8.png)

![image](https://user-images.githubusercontent.com/58553711/226596766-4f69868e-d996-4dd0-9960-bd189d2fd172.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DilsherB** [comment]
@Reem-lab 
Thank you very much for your kind review. both the issues are fixed now.
![image](https://user-images.githubusercontent.com/41000844/226602264-2fc2b9fe-d5ac-4c76-aa99-e214c2382b5a.png)

**Comment by GzimAsani** [comment]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- NA
### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by DilsherB** [comment]
solved
